"""Initial

Revision ID: c918a5b46c80
Revises: 
Create Date: 2022-04-16 22:25:52.826896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c918a5b46c80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.create_unique_constraint(None, 'jobs', ['id'])
    op.create_unique_constraint(None, 'posts', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'jobs', type_='unique')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_photo_url_hd', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('biography', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('external_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('business_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_approx', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age_group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('langs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_private', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_business_account', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_company', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('followers_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followings_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('posts_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('highlight_reels_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latest_location_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###
