name: test-github-actions
on: 
  push:
    branches:
      - master
jobs: 
  test: 
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3
      - run: chmod 774 *.sh
      - run: ./delploy.sh
      - run: ./migrate.sh