name: test-github-actions
on: 
  push:
    branches:
      - master
jobs: 
  test: 
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3
      - run: docker-compose -f ./docker-compose.dev.yaml up  --build --force-recreate -d
      - run: docker-compose -f ./docker-compose.dev.yaml ps -a

    
