name: test-github-actions
on: 
  push:
    branches:
      - master
jobs: 
  test: 
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3
      - run: docker-compose -f ./docker-compose.dev.yaml up  --build --force-recreate -d
      - run: docker-compose -f ./docker-compose.dev.yaml ps -a
      - run: docker exec -i backend_server_1 /bin/bash -c "alembic stamp head"
      - run: docker exec -i backend_server_1 /bin/bash -c "alembic revision --message='Update migrate in github action' --autogenerate"
      - run: docker exec -i backend_server_1 /bin/bash -c "alembic upgrade head"

    
